# Generated by Django 5.1.5 on 2025-01-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPSThingToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nps_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('topics', models.JSONField(default=list)),
                ('activities', models.JSONField(default=list)),
                ('season', models.CharField(blank=True, max_length=255, null=True)),
                ('age_recommendation', models.CharField(blank=True, max_length=50, null=True)),
                ('accessibility', models.TextField(blank=True, null=True)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('raw_data', models.JSONField()),
            ],
        ),
    ]
