# Generated by Django 5.1.5 on 2025-02-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_npsthingtodo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npsthingtodo',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='npsthingtodo',
            name='nps_id',
        ),
        migrations.RemoveField(
            model_name='npsthingtodo',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='npsthingtodo',
            name='season',
        ),
        migrations.RemoveField(
            model_name='npsthingtodo',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='npsthingtodo',
            name='topics',
        ),
    ]
