# Generated by Django 5.1.5 on 2025-01-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_npsthingtodo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='npsthingtodo',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
