# Generated by Django 5.1.5 on 2025-02-04 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_npsthingtodo_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npsthingtodo',
            name='age_recommendation',
        ),
    ]
