# Generated by Django 5.1.5 on 2025-01-30 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_npsthingtodo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npsthingtodo',
            name='location',
        ),
    ]
