# Generated by Django 5.1.5 on 2025-02-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_npsthingtodo_age_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='npsthingtodo',
            name='nps_id',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
