# Generated by Django 5.1.5 on 2025-02-05 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_npsthingtodo_nps_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='npsthingtodo',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
