# Generated by Django 5.1.5 on 2025-02-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_npsthingtodo_submitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npsthingtodo',
            name='submitter',
        ),
        migrations.AddField(
            model_name='customuser',
            name='submitted_activities',
            field=models.ManyToManyField(blank=True, related_name='submitted_by_users', to='core.npsthingtodo'),
        ),
        migrations.AlterField(
            model_name='npsthingtodo',
            name='accessibility',
            field=models.BooleanField(default=False),
        ),
    ]
