# Generated by Django 5.1.5 on 2025-02-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_npsthingtodo_submitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npsthingtodo',
            name='nps_id',
            field=models.CharField(max_length=255),
        ),
    ]
