# Generated by Django 5.1.5 on 2025-02-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_npsthingtodo_nps_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npsthingtodo',
            name='accessibility',
        ),
        migrations.RemoveField(
            model_name='npsthingtodo',
            name='pets_allowed',
        ),
    ]
