# Generated by Django 5.1.5 on 2025-02-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_npsthingtodo_accessibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npsthingtodo',
            name='passes_qc',
            field=models.BooleanField(default=False),
        ),
    ]
